name: iqsaat
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  animated_splash_screen: ^1.1.0
  google_maps_flutter: 0.5.21+17
  flutter_rating_bar: ^3.0.1+1
  carousel_slider: ^2.0.0
  carousel_pro: ^1.0.0
  flutter_polyline_points: ^0.2.4
  flutter_staggered_grid_view: ^0.3.4
  geocoding: ^1.0.5 
  badges: ^1.2.0
  provider: ^4.0.5+1
  persistent_bottom_nav_bar: ^4.0.2
  bezier_chart:
  geolocator: ^5.3.1
  permission: ^0.1.7
  video_thumbnail: ^0.2.1
  file_picker: 1.6.3+2
  font_awesome_flutter: ^8.8.1
  dotted_border: ^1.0.6
  country_code_picker: ^1.4.0
  fluttertoast: ^7.0.4
  pluto_grid:
  shared_preferences: ^0.5.10
  flutter_datetime_picker: ^1.4.0
  pdf: ^1.5.0
  mailer: ^3.0.4
  image_picker: ^0.6.7+22
  percent_indicator: "^2.1.7+2"
  flutter_swiper: ^1.1.6
  timeago: ^2.0.26
  fl_chart: ^0.12.0
  socket_io_client: ^0.9.12

  
  
  #hive db
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  hive_generator: ^0.8.0
  build_test: ^0.10.3
  cached_network_image: ^2.0.0
  zefyr: ^0.12.0
  quill_delta: ^1.0.0
  flutter_screenutil: ^0.5.3
  mask_text_input_formatter: ^1.2.1
  flutter_switch: ^0.3.1
  tuple: ^2.0.0
  select_form_field: ^2.0.0
  awesome_card: ^1.1.5
  smooth_page_indicator: ^0.2.3
dependency_overrides:

dev_dependencies:
  build_runner: ^1.10.2
  json_serializable: ^3.5.1 
  flutter_test:
    sdk: flutter
  animated_text_kit: ^2.0.0
  google_fonts: ^1.0.0
  dio: ^3.0.9
  http:

flutter:
  uses-material-design: true

  assets:
   - assets/appIcons/
   - assets/MapDesign/
   - assets/images/
   - assets/images/cartImages/
   - assets/images/brandImages/