/// Flutter icons NavBarIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavBarIcons
///      fonts:
///       - asset: fonts/NavBarIcons.ttf
///
/// 
/// 
/// 
///
///
// @dart=2.9
import 'package:flutter/widgets.dart';

class NavBarIcons {
  NavBarIcons._();

  static const _kFontFam = 'NavBarIcons';
  static const String _kFontPkg = null;

  static const IconData flashdeals = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myeve = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
